[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "swoosh"
version = "0.1.0"
description = "Dead simple docs generator"
authors = [{"name"= "ARJ"}]
dependencies = ['click']

[project.scripts]
swoosh = "swoosh:main"
